# Generated by Django 5.1.3 on 2025-01-05 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Histroy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=255)),
                ('question', models.TextField()),
                ('respons', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='TestUPFILE',
        ),
    ]
