# Generated by Django 5.1.3 on 2025-01-05 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0002_histroy_delete_testupfile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Histroy',
            new_name='History',
        ),
    ]
