# Generated by Django 5.1.3 on 2025-01-22 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0003_rename_histroy_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('splitter', models.CharField(help_text='Enter the splitter', max_length=100)),
                ('chunksize', models.IntegerField(help_text='Enter the chunk size')),
                ('overlap', models.FloatField(help_text='Enter the overlap value')),
                ('temp', models.FloatField(help_text='Set the temperature (0.0 to 1.0)')),
            ],
        ),
    ]
