# Generated by Django 5.1.3 on 2025-01-22 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0004_uservalues'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uservalues',
            name='splitter',
            field=models.CharField(choices=[('comma', 'Comma'), ('space', 'Space'), ('newline', 'Newline'), ('tab', 'Tab')], default='comma', help_text='Select the splitter', max_length=50),
        ),
    ]
