# Generated by Django 5.1.3 on 2025-01-24 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0006_alter_uservalues_splitter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uservalues',
            name='overlap',
            field=models.IntegerField(help_text='Enter the overlap value'),
        ),
    ]
