# Generated by Django 5.1.3 on 2025-01-28 20:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0007_alter_uservalues_overlap'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='chunks',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
